### ISSUE TITLE
Object-like syntax

### ISSUE THREAD

**Issue by tejasbubane** [MinimaHQ/re-classnames#8]
In relation to #4, would it be better to support a variant of `make` which takes second argument as a `Js.Dict` whose keys are classnames & values are booleans?

```re
let classes = Js.Dict.fromList([("a", true), ("b", false)]);
Cn.make(["one", "two"], classes); 
```

or just a list of tuples:
```re
let classes = [("a", true), ("b", false)];
Cn.make(["one", "two"], classes); 
```

**Comment by alexfedoseev** [comment]
Can you elaborate on use cases and why `Cn.ifTrue` doesn’t work for you?

**Comment by tejasbubane** [comment]
Sorry for being unclear. What I really meant was providing another API with some function like `makeWithDict` which accepts a dictionary object. 

`Cn.ifTrue` definitely works and I am not saying we should change it.

**Comment by alexfedoseev** [comment]
@tejasbubane It's definitely possible by introducing `Cn.dict`:

```reason
Cn.make([
  dict->Cn.dict,
  // ...
]) 
```

But I'm wondering what use-cases you have in mind? I've been writing Reason for more than 3 years I think and never felt a need in putting things in `Js.Dict`. Interop maybe?

Don't get me wrong, I would happily add this bit to the api. I'm just not a big fan of adding things for the sake of adding things.

**Comment by tejasbubane** [comment]
I just meant to have an alternate syntax. But keeping things minimal also makes sense. Thanks.
